# Generated by Django 5.0.2 on 2024-03-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatGPT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='session_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
